### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by antrix190** [2DSharp/Quizatron#9]
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/workspace/Quizatron/src/main/java/me/twodee/quizatron/Main.java:[17,1] cannot find symbol
  symbol:   static getResource
  location: class
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.571 s
[INFO] Finished at: 2018-10-14T23:13:53+05:30
[INFO] Final Memory: 18M/149M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Quizatron: Compilation failure
[ERROR] /D:/workspace/Quizatron/src/main/java/me/twodee/quizatron/Main.java:[17,1] cannot find symbol
[ERROR] symbol:   static getResource
[ERROR] location: class
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

I get this error message when i run mvn clean install.

**Comment by 2DSharp** [comment]
Hi, can you post the output of `mvn clean install  -e`?

**Comment by 2DSharp** [comment]
I don't seem to be able to reproduce this error. Please post the output of the previous comment. And did you try with the original installation instructions? @antrix190

**Comment by 2DSharp** [comment]
@antrix190 https://github.com/2DSharp/Quizatron/pull/10 should probably fix your problem, please try to get the new version and check if it works.

**Comment by 2DSharp** [comment]
Closing this issue, should be fixed in the latest update. Haven't been able to reproduce it. Feel free to reopen it if the error still persists.
